import { describe, expect, it } from 'vitest';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import {
  DESCRIPTION_MAX,
  DESCRIPTION_MIN,
  HEADLINE_MAX_WORDS,
  TITLE_MAX,
  buildPins,
  validatePins,
} from './pins';
import { listPublished } from '@/lib/content/mdx';

/**
 * The pin set, checked at source level.
 *
 * Pinterest silently truncates an over-long title and an over-short
 * description reads as spam, so the limits are worth failing a build over
 * rather than discovering in the account. The image files themselves are
 * regenerated by `npm run pins`; what is tested here is the data behind them.
 */
describe('pinterest pins', () => {
  const pins = buildPins();

  it('has two pins for every published page', () => {
    const published =
      listPublished('blog').length + listPublished('tools').length + listPublished('crops').length;
    expect(pins).toHaveLength(published * 2);
  });

  it('passes its own validation', () => {
    expect(validatePins(pins)).toEqual([]);
  });

  it('never pins a draft', () => {
    const live = new Set(
      (['blog', 'tools', 'crops'] as const).flatMap((kind) =>
        listPublished(kind).map((entry) => `${kind}/${entry.slug}`),
      ),
    );
    for (const pin of pins) {
      expect(live.has(`${pin.kind}/${pin.slug}`), `${pin.file} points at an unpublished page`).toBe(
        true,
      );
    }
  });

  it.each(pins)('$file fits what Pinterest accepts', (pin) => {
    expect(pin.headline.split(' ').length).toBeLessThanOrEqual(HEADLINE_MAX_WORDS);
    expect(pin.title.length).toBeLessThanOrEqual(TITLE_MAX);
    expect(pin.description.length).toBeGreaterThanOrEqual(DESCRIPTION_MIN);
    expect(pin.description.length).toBeLessThanOrEqual(DESCRIPTION_MAX);
    expect(pin.url.startsWith('https://')).toBe(true);
    expect(pin.url.endsWith('/')).toBe(true);
  });

  it('names the page keyword in every description, and only once', () => {
    for (const pin of pins) {
      // The hook is built around the keyword, so its absence means the
      // description drifted away from what the page is trying to rank for.
      const haystack = pin.description.toLowerCase();
      const needle = pin.slug.split('-')[0]!;
      expect(haystack.includes(needle) || haystack.includes('soilsums'), pin.file).toBe(true);
    }
  });

  it('has no hashtag lists', () => {
    for (const pin of pins) {
      expect(pin.description, pin.file).not.toMatch(/#\w/);
    }
  });

  it('gives the two variants of a page different headlines and support', () => {
    const byPage = new Map<string, typeof pins>();
    for (const pin of pins) {
      const key = `${pin.kind}/${pin.slug}`;
      byPage.set(key, [...(byPage.get(key) ?? []), pin]);
    }
    for (const [key, group] of byPage) {
      expect(group[0]!.headline, key).not.toEqual(group[1]!.headline);
      expect(group[0]!.description, key).not.toEqual(group[1]!.description);
    }
  });

  it('has an image on disk for every pin', () => {
    for (const pin of pins) {
      expect(existsSync(join('public', 'pins', pin.file)), `missing ${pin.file}`).toBe(true);
    }
  });
});
