import type { Metadata } from 'next';
import { absoluteUrl, site } from './site';

export const TITLE_MAX = 60;
export const DESCRIPTION_MAX = 155;

/**
 * Builds a page's metadata: unique title and description, canonical URL, Open
 * Graph and Twitter card tags.
 *
 * Titles are written to fit within 60 characters and descriptions within 155
 * on their own; in development we shout if one does not, and
 * `npm run content-report` fails the same way in CI.
 */
export function pageMetadata({
  title,
  description,
  path,
  canonicalPath,
  ogImage = '/og-default.png',
  noIndex = false,
}: {
  title: string;
  description: string;
  path: string;
  /** Canonical URL, when it should differ from this page's own path. */
  canonicalPath?: string;
  /** Path to a 1200x630 PNG in public/. Generated by scripts/generate-og.ts. */
  ogImage?: string;
  noIndex?: boolean;
}): Metadata {
  if (process.env.NODE_ENV === 'development') {
    if (title.length > TITLE_MAX) {
      console.warn(`[seo] title is ${title.length} chars (max ${TITLE_MAX}): ${title}`);
    }
    if (description.length > DESCRIPTION_MAX) {
      console.warn(
        `[seo] description is ${description.length} chars (max ${DESCRIPTION_MAX}): ${description}`,
      );
    }
  }

  const url = absoluteUrl(path);
  const canonical = absoluteUrl(canonicalPath ?? path);
  const images = [
    {
      url: `${site.url}${ogImage}`,
      width: 1200,
      height: 630,
      alt: `${site.name} — ${site.tagline}`,
    },
  ];

  return {
    title,
    description,
    alternates: { canonical },
    openGraph: {
      type: 'website',
      siteName: site.name,
      title,
      description,
      url,
      locale: site.locale,
      images,
    },
    twitter: { card: 'summary_large_image', title, description, images },
    ...(noIndex ? { robots: { index: false, follow: true } } : {}),
  };
}
